spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/service
    password: root
  cloud:
    config:
      enabled: 'false'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop